version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - 5173:5173
  backend:
    build: ./backend
    volumes:
      - ./backend:/sample-mern-backend
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=secretnoclue
